# Generated by Django 4.2.7 on 2023-12-14 20:31

from django.db import migrations, models
import students.managers


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="student",
            managers=[
                ("objects", students.managers.StudentUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "A user is already registered with this email address"
                },
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
