# Generated by Django 4.2.7 on 2023-12-15 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_student_options_alter_student_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table=None,
        ),
    ]
