# Generated by Django 4.2.7 on 2023-12-15 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_student_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="auth_user",
        ),
    ]
