# Generated by Django 4.2.7 on 2023-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_alter_student_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Почта уже зарегистрирована на сайте!"},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
