# Generated by Django 4.2.7 on 2023-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(max_length=10)),
                ('session_type', models.PositiveSmallIntegerField(default=0)),
                ('subgroup', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
    ]
