# Generated by Django 4.2.7 on 2023-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="session_type",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="short_title",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="subgroup",
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="time_end",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="time_start",
            field=models.DateTimeField(blank=True),
        ),
    ]
