# Generated by Django 4.2.7 on 2023-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_studysession_session_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="comment",
            field=models.TextField(blank=True, default="Здесь могла быть ваша заметка"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="short_title",
            field=models.CharField(blank=True, default="ПРДМТ", max_length=10),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="subgroup",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="time_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="time_start",
            field=models.DateTimeField(),
        ),
    ]
