# Generated by Django 4.2.7 on 2023-11-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_alter_studysession_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="comment",
            field=models.TextField(
                blank=True, default="Здесь могла быть ваша заметка", null=True
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="session_type",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="short_title",
            field=models.CharField(
                blank=True, default="ПРДМТ", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="subgroup",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
